account/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout')
]

author/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('new/', views.CreateAuthor.as_view(), name='newauthor'),
]

book/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ListBooks.as_view(), name='index'),
    path('new/', views.CreateNewbook.as_view(), name='newbook'),
    path('<int:pk>/<str:status>/', views.ChangeStatus.as_view(), name='status'),
    path('filter/', views.FilterBooks.as_view(), name='filter'),
    path('search/', views.SearchBooks.as_view(), name='search'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
    path('account/', include('account.urls')),
    path('author/', include('author.urls')),
]

account/models.py
from django.db import models

# Create your models here.

author/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

book/models.py
from author.models import Author
import re
from django.db import models
from django.core.exceptions import ValidationError
Q = models.Q


class BookManager(models.Manager):
    def filter_book(self, pk_author, status):
        books = self.all()
        available_authors = Author.objects.all()

        if status == 'available' or status == 'on_loan':
            books = books.filter(status=status)
            available_authors = Author.objects.filter(
                book_author__status=status).distinct()

        if pk_author and pk_author.isdigit():
            books = books.filter(author=pk_author)

        return books, available_authors

    def search_title_isbn(self, search):
        books = self.filter(
            Q(title__icontains=search) |
            Q(isbn__icontains=search)
        )
        return books


def validate_ibns(value):
    regex = r"^\d{9}[\dX]$|^\d{13}$"
    isbn = value.replace("-", "").replace(" ", "")

    if not re.fullmatch(regex, isbn):
        raise ValidationError("O ISBN deve ter 10 ou 13 dígitos.")

    if len(isbn) == 10:  # Validação ISBN-10
        total = sum((10 - i) * (10 if x == "X" else int(x))
                    for i, x in enumerate(isbn))
        if total % 11 != 0:
            raise ValidationError("O ISBN-10 informado não é válido.")

    elif len(isbn) == 13:  # Validação ISBN-13
        total = sum((1 if i % 2 == 0 else 3) * int(x)
                    for i, x in enumerate(isbn))
        if total % 10 != 0:
            raise ValidationError("O ISBN-13 informado não é válido.")


class Book(models.Model):
    STATUS_CHOICES = [
        ('available', 'disponível'),
        ('on_loan', 'emprestado'),
    ]
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        Author, on_delete=models.PROTECT, related_name='book_author')
    isbn = models.CharField(max_length=16, unique=True,
                            validators=[validate_ibns])
    publication_date = models.DateField()
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='available',)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = BookManager()

    def __str__(self):
        return f"{self.title} ({self.isbn})"

author/forms.py
from django import forms

from .models import Author


class AuthorForms(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('name', 'bio',)

book/forms.py
from django import forms

from .models import Book, Author


class BookForms(forms.ModelForm):
    def __init__(self, *args, is_filter=False, **kwargs):
        super().__init__(*args, **kwargs)

        if is_filter:
            self.fields['author'].queryset = Author.objects.all()
            self.fields['author'].empty_label = "Todos"
        else:
            self.fields['author'].queryset = Author.objects.all()

    publication_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    status = forms.ChoiceField(
        choices=[('', 'Todos')] + Book.STATUS_CHOICES, required=False)

    class Meta:
        model = Book
        fields = '__all__'

account/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout


class Login(View):
    def get(self, request):
        forms = AuthenticationForm()

        return render(request, 'account/pages/login.html', {"forms": forms})

    def post(self, request):
        login_user = AuthenticationForm(request, data=request.POST)

        if login_user.is_valid():
            user = login_user.get_user()
            login(request, user)
            return redirect('index')

        return render(request, 'account/pages/login.html', {"forms": login_user})


class Logout(View):
    def get(self, request):
        logout(request)
        return redirect('index')

author/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Author
from .forms import AuthorForms


class CreateAuthor(LoginRequiredMixin, CreateView):
    model = Author
    form_class = AuthorForms
    template_name = 'author/pages/create_author.html'
    context_object_name = 'form'
    success_url = '/new/'
    login_url = '/account/login/'

base/views.py
from django.shortcuts import render

book/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.views.generic import ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from .models import Book
from .forms import BookForms


# Create your views here.

class ListBooks(ListView):
    model = Book
    template_name = 'book/pages/index.html'
    context_object_name = 'books'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = BookForms(is_filter=True)
        return context


class FilterBooks(View):
    def get(self, request):
        pk_author = request.GET.get('author')
        status = request.GET.get('status')
        books, available_authors = Book.objects.filter_book(pk_author, status)
        books = get_list_or_404(books)
        form = BookForms(initial={'author': pk_author, 'status': status})
        form.fields['author'].queryset = available_authors
        return render(request, 'book/pages/index.html', {'books': books, 'form': form})


class SearchBooks(View):
    def get(self, request):
        search = request.GET.get('q')
        books = Book.objects.search_title_isbn(search)
        form = BookForms()

        return render(request, 'book/pages/index.html', {'books': books, 'form': form})


class ChangeStatus(View):
    def get(self, request, pk, status):
        book = get_object_or_404(Book, pk=pk)
        book.status = status
        book.save()

        return redirect('index')


class CreateNewbook(LoginRequiredMixin, CreateView):
    model = Book
    form_class = BookForms
    template_name = 'book/pages/create_book.html'
    success_url = '/'
    login_url = '/account/login/'

author/templates/author/pages/create_author.html
{% extends "base/pages/base.html" %}

{% block head_title %}Cadastrar{% endblock head_title %}

{% block main_content %}
    <section class="form-login container">
        <form method="post">
            {% csrf_token %}
            <label for="name">
                <span>Nome do Autor:</span>
                {{form.name}}
            </label>
            <label for="id_bio">
                <span>Biografia:</span>
                {{form.bio}}
            </label>
            <button type="submit" class="btn">Cadastrar</button>
        </form>
        <div class="error">
            {% if forms.non_field_errors %}
                <ul class="errorlist">
                    {% for error in forms.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </section>
{% endblock main_content %}

base/templates/base/pages/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    {% include "base/partials/head_config.html" %}
    <title>{% block head_title %}{% endblock head_title %}</title>
</head>
<body>
    <header>
       {% include "base/partials/header_body.html" %}
    </header>
    <main>
        {% block main_content %}{% endblock main_content %}
    </main>
    <footer></footer>
</body>
</html>

base/templates/base/partials/head_config.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<link rel="stylesheet" href="{% static "base/css/style.css" %}">
<script defer src="{% static "base/js/main.js" %}"></script>

base/templates/base/partials/header_body.html
<div>
    <i class="bi bi-book-half"></i>
    <h1>
        <strong>Library</strong>
        <span>Manager</span>
    </h1>
</div>
<nav class="container">
    <ul>
        {% if user.is_authenticated %}
            {% include "base/partials/login.html" %}
        {% else %}
            {% include "base/partials/logout.html" %}
        {% endif %}
    </ul>
    <input type="checkbox" id="check" hidden>
    <div class="search">
        <form method="get" action="{% url "search" %}">
            <input type="text" name="q" placeholder="faça sua pesquisa" class="search">
            <button type="submit" class="btn">Buscar</button>
            <label for="check" class="btn">
                <i class="bi bi-x-lg"></i>
            </label>
        </form>
    </div>
    <label for="check" class="overlay"></label>
    <label for="check">
        <i class="bi bi-search"></i>
    </label>
</nav>

base/templates/base/partials/login.html
<li>
    <a href="{% url "index" %}">Home</a>
</li>
<li>
    <a href="{% url "newbook" %}">Cadastrar Livros</a>
</li>
<li>
    <a href="{% url "logout" %}">Logout</a>
</li>

base/templates/base/partials/logout.html
<li>
    <a href="{% url "index" %}">Home</a>
</li>
<li>
    <a href="{% url "login" %}">Login</a>
</li>

book/templates/book/pages/create_book.html
{% extends "base/pages/base.html" %}
{% block head_title %}Cadastrar novo Livro{% endblock head_title %}
{% block main_content %}
    <section class="create-book container">
        <form method="post">
            {% csrf_token %}
            <label for="id_title">
                <span>Título do Livro:</span>
                {{form.title}}
            </label>
            <label for="id_author">
                <span>Autor: </span>
                {{form.author}}
                <a href="{% url "newauthor" %}"><i class="bi bi-plus-circle-fill"></i></a>
            </label>
            <label for="id_isbn">
                <span>isbn</span>
                {{form.isbn}}
            </label>
            <label for="id_publication_date">
                <span>Publicado em:</span>
                {{form.publication_date}}
            </label>
            <button type="submit" class="btn">Cadastrar</button>
        </form>
    </section>
{% endblock main_content %}

book/templates/book/pages/index.html
{% extends "base/pages/base.html" %}
{% block head_title %}BookStore{% endblock head_title %}
{% block main_content %}
<section class="list-books container">
    <form action="{% url "filter" %}" method="get" id="filter">
        {{form.author}}
        {{form.status}}
    </form>
    <table>
        <thead>
            <tr>
                <th>Nome do Livro</th>
                <th>Author</th>
                <th>Disponibilidade</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books  %}
                <tr>
                    <td title="{{book.isbn}}">{{book.title}}</td>
                    <td>{{book.author}}</td>
                    <td>{{book.get_status_display}}</td>
                    <td>
                        <a href="{% url "status" pk=book.pk status='on_loan' %}">emprestar</a>
                        <a href="{% url "status" pk=book.pk status='available' %}">devolver</a>
                    </td>
                </tr>
            {% empty %}
                <p>Não Há Livros!!!!</p>
            {% endfor %}
        </tbody>
    </table>
</section>
{% endblock main_content %}